name: Check Docker

on: push

jobs:
    Check:
        runs-on: ubuntu-latest
        steps:
            - name: Check
              run: docker info

            - name: Run deploy workflow
              run: |
                 curl -X POST \
                 -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                 -H "Accept: application/vnd.github.v3+json" \
                 https://api.github.com/repos/${{ github.repository_owner }}/${{ github.repository }}/dispatches \
                 -d '{"event_type":"deploy_workflow","client_payload":{"unit":false,"integration":true}}'

                #  curl -L \
                #     -X POST \
                #     -H "Accept: application/vnd.github+json" \
                #     -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                #     https://api.github.com/repos/OWNER/REPO/dispatches \
                #     -d '{"event_type":"on-demand-test","client_payload":{"unit":false,"integration":true}}'